apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 150-openshift
spec:
  modules:
    - name: ibm-resource-group
      alias: hpcs_resource_group
      variables:
        - name: provision
          value: false
      version: v2.3.0
    - name: hpcs
      alias: hpcs
      variables:
        - name: provision
          value: false
        - name: region
          alias: hpcs_region
      dependencies:
        - name: resource_group
          ref: hpcs_resource_group
      version: v1.2.1
    - name: ibm-kms-key
      variables:
        - name: name
          required: true
      version: v1.2.0
    - name: ibm-resource-group
      variables:
        - name: provision
          value: false
      version: v2.3.0
    - name: ibm-vpc
      variables:
        - name: provision
          value: false
        - name: name
          required: true
      version: v1.11.5
    - name: ibm-vpc-subnets
      alias: workload-subnets
      variables:
        - name: _count
          value: 3
        - name: label
          value: workload
        - name: provision
          value: false
      version: v1.8.0
    - name: ibm-ocp-vpc
      variables:
        - name: disable_public_endpoint
          value: true
        - name: kms_enabled
          value: true
      dependencies:
        - name: subnets
          ref: workload-subnets
        - name: kms_key
          ref: kms_key
        - name: resource-group
          ref: resource_group
        - name: cos
          ref: cos
        - name: sync
          ref: sync
      version: v1.9.0
    - name: ibm-resource-group
      alias: cs_resource_group
      variables:
        - name: provision
          value: false
      version: v2.3.0
    - name: ibm-object-storage
      alias: cos
      variables:
        - name: provision
          value: false
        - name: name_prefix
          alias: cs_name_prefix
          scope: global
      dependencies:
        - name: resource_group
          ref: cs_resource_group
      version: v3.3.2
  variables:
    - name: resource_group_name
    - name: region
    - name: ibmcloud_api_key
    - name: worker_count
    - name: hpcs_name
    - name: name_prefix
      required: true
    - name: kms_key_id
      required: true
