apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 150-openshift
spec:
  modules:
    - name: ibm-resource-group
      alias: hpcs_resource_group
      variables:
        - name: provision
          value: false
    - name: hpcs
      variables:
        - name: provision
          value: false
        - name: region
          alias: hpcs_region
      dependencies:
        - name: resource_group
          ref: hpcs_resource_group
    - name: ibm-resource-group
      variables:
        - name: provision
          value: false
    - name: ibm-vpc
      variables:
        - name: provision
          value: false
        - name: name
          required: true
    - name: ibm-vpc-subnets
      alias: workload-subnets
      variables:
        - name: _count
          value: 3
        - name: label
          value: workload
        - name: provision
          value: false
    - name: ibm-ocp-vpc
      variables:
        - name: disable_public_endpoint
          value: true
        - name: kms_key_id
          required: true
      dependencies:
        - name: subnets
          ref: workload-subnets
        - name: resource-group
          ref: resource_group
        - name: cos
          ref: cos
        - name: vpc
          ref: ibm-vpc
        - name: kms
          ref: key-protect
  variables:
    - name: resource_group_name
    - name: region
    - name: ibmcloud_api_key
    - name: worker_count
    - name: hpcs_name
    - name: name_prefix
      required: true
