apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 170-ibm-fs-openshift-gitops
  labels:
    type: infrastructure
    code: '170'
  annotations:
    displayName: OpenShift GitOps (ArgoCD)
    description: Provision GitOps (ArgoCD) on OpenShift
    vpn/required: 'true'
spec:
  modules:
    - name: ocp-login
      alias: cluster
      version: v1.2.13
      variables:
        - name: server_url
          required: true
        - name: login_user
          value: apikey
        - name: login_password
          alias: ibmcloud_api_key
          scope: global
    - name: namespace
      alias: tools_namespace
      version: v3.2.3
      default: true
      variables:
        - name: name
          value: tools
    - name: cluster-config
      alias: config
      version: v0.1.2
      variables:
        - name: banner_text
          value: Workload
        - name: banner_background_color
          value: red
    - name: openshift-cicd
      alias: openshift-cicd
      version: v1.11.0
    - name: olm
      version: v1.3.2
    - name: namespace
      alias: openshift-gitops
      version: v3.2.3
    - name: namespace
      alias: sealed-secret
      version: v3.2.3
    - name: sealed-secret-cert
      version: v1.0.1
  variables:
    - name: server_url
      type: string
      description: The url for the OpenShift api
    - name: cluster_login_token
      type: string
      description: Token used for authentication
      sensitive: true
    - name: config_banner_text
      type: string
      description: Text that should be shown in the banner on the cluster
      defaultValue: Workload
    - name: openshift-gitops_name
      type: string
      description: The namespace that should be created
    - name: sealed-secret_name
      type: string
      description: The namespace that should be created
      defaultValue: sealed-secrets
