apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 110-edge-vpc
  labels:
    platform: ibm
    code: 110
  annotations:
    displayName: Edge VPC
    description: Edge VPC with VPN and Bastion servers
spec:
  modules:
    - name: ibm-resource-group
      alias: kms_resource_group
      variables:
        - name: provision
          value: false
      version: v3.0.1
    - name: ibm-resource-group
      alias: at_resource_group
      variables:
        - name: provision
          value: false
      version: v3.0.1
    - name: ibm-kms
      alias: kms
      variables:
        - name: provision
          value: false
        - name: region
          alias: kms_region
        - name: name_prefix
          alias: kms_name_prefix
          scope: global
          value: ''
      dependencies:
        - name: resource_group
          ref: kms_resource_group
      version: v0.3.2
    - name: ibm-resource-group
      variables:
        - name: resource_group_name
          alias: edge_resource_group_name
          scope: global
        - name: provision
          alias: edge_resource_group_provision
          scope: global
      version: v3.0.1
    - name: ibm-access-group
      version: v3.0.0
    - name: ibm-vpc
      variables:
        - name: address_prefix_count
          value: 3
        - name: address_prefixes
          value:
            - 10.1.0.0/18
            - 10.2.0.0/18
            - 10.3.0.0/18
      version: v1.13.0
    - name: ibm-flow-logs
      dependencies:
        - name: target
          ref: ibm-vpc
        - name: cos_bucket
          ref: flow_log_bucket
        - name: resource_group
          ref: resource_group
        - name: auth
          ref: auth
      version: v1.0.0
    - name: ibm-vpc-gateways
      version: v1.6.1
    - name: ibm-vpc-subnets
      alias: ingress-subnets
      variables:
        - name: _count
          value: 3
        - name: label
          value: ingress
        - name: ipv4_cidr_blocks
          value:
            - 10.1.10.0/24
            - 10.2.10.0/24
            - 10.3.10.0/24
      dependencies:
        - name: gateways
          ref: ibm-vpc-gateways
        - name: resource-group
          ref: resource_group
        - name: vpc
          ref: ibm-vpc
      version: v1.9.4
    - name: ibm-vpc-subnets
      alias: bastion-subnets
      variables:
        - name: _count
          value: 3
        - name: label
          value: bastion
        - name: ipv4_cidr_blocks
          value:
            - 10.1.20.0/24
            - 10.2.20.0/24
            - 10.3.20.0/24
      version: v1.9.4
    - name: ibm-vpc-subnets
      alias: egress-subnets
      variables:
        - name: _count
          value: 3
        - name: label
          value: egress
        - name: ipv4_cidr_blocks
          value:
            - 10.1.30.0/24
            - 10.2.30.0/24
            - 10.3.30.0/24
      version: v1.9.4
    - name: ibm-vpc-vpn-gateway
      dependencies:
        - name: subnets
          ref: ingress-subnets
        - name: resource_group
          ref: resource_group
      version: v1.1.2
    - name: ibm-vpn-server
      dependencies:
        - name: subnets
          ref: ingress-subnets
        - name: ibm-cert-manager
          ref: cert-manager
        - name: resource_group
          ref: resource_group
        - name: cert-manager
          ref: ibm-cert-manager
      version: v0.0.11
    - name: ibm-vpc-ssh
      alias: edge_ssh_bastion
      variables:
        - name: label
          value: bastion
      version: v1.7.1
    - name: vsi-bastion
      variables:
        - name: image_name
          scope: module
        - name: kms_enabled
          value: true
      dependencies:
        - name: subnets
          ref: bastion-subnets
        - name: vpcssh
          ref: edge_ssh_bastion
        - name: resource_group
          ref: resource_group
        - name: vpc
          ref: ibm-vpc
        - name: kms_key
          ref: kms-key
      version: v1.9.0
    - name: ibm-resource-group
      alias: cs_resource_group
      variables:
        - name: provision
          value: false
      version: v3.0.1
    - name: ibm-object-storage
      alias: cos
      variables:
        - name: provision
          value: false
        - name: name_prefix
          alias: cs_name_prefix
          scope: global
      dependencies:
        - name: resource_group
          ref: cs_resource_group
      version: v4.0.0
    - name: ibm-kms-key
      variables:
        - name: provision
          value: true
      dependencies:
        - name: kms
          ref: kms
      version: v1.5.0
    - name: ibm-activity-tracker
      variables:
        - name: provision
          value: false
      dependencies:
        - name: resource_group
          ref: at_resource_group
      version: v2.4.0
    - name: sysdig
      variables:
        - name: provision
          value: false
        - name: name_prefix
          alias: cs_name_prefix
          scope: global
      dependencies:
        - name: resource_group
          ref: cs_resource_group
      version: v4.0.1
    - name: ibm-cert-manager
      variables:
        - name: provision
          value: false
        - name: name_prefix
          alias: cs_name_prefix
          scope: global
      dependencies:
        - name: resource_group
          ref: cs_resource_group
        - name: kms_key
          ref: kms-key
      version: v1.1.0
    - name: ibm-object-storage-bucket
      alias: flow_log_bucket
      variables:
        - name: label
          value: flow-logs
        - name: allowed_ip
          value:
            - 0.0.0.0/0
      version: v0.8.2
    - name: ibm-transit-gateway
      variables:
        - name: name_prefix
          alias: cs_name_prefix
          scope: global
      dependencies:
        - name: resource-group
          ref: cs_resource_group
        - name: vpc
          ref: '*'
      version: v0.2.2
  variables:
    - name: edge_resource_group_name
    - name: edge_resource_group_provision
    - name: region
    - name: ibmcloud_api_key
    - name: name_prefix
      alias: edge_name_prefix
      required: true
      scope: global
    - name: cs_resource_group_name
    - name: cs_name_prefix
    - name: kms_service
    - name: edge_ssh_bastion_public_key
      value: ''
    - name: edge_ssh_bastion_private_key
      value: ''
    - name: edge_ssh_bastion_public_key_file
    - name: edge_ssh_bastion_private_key_file
