apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 170-openshift-argocd
spec:
  modules:
    - name: ocp-login
      variables:
        - name: server_url
          required: true
        - name: login_user
          value: apikey
        - name: login_password
          alias: ibmcloud_api_key
          scope: global
      version: v1.2.4
    - name: namespace
      variables:
        - name: name
          value: tools
      version: v3.1.3
    - name: cluster-config
      alias: config
      variables:
        - name: banner_text
          value: Workload
        - name: banner_background_color
          value: red
      version: v0.1.2
    - name: argocd
      version: v2.17.9
  variables:
    - name: config_banner_text
