apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 160-ibm-fs-openshift-dev-tools
  labels:
    type: infrastructure
    platform: ibm
    code: '160'
  annotations:
    displayName: OpenShift Developer Tools
    description: Open-Source collection of assets for application development on OpenShift
spec:
  modules:
    - name: ibm-resource-group
      alias: resource_group
      version: v3.2.15
      variables: &ref_0
        - name: provision
          value: false
        - name: resource_group_name
          alias: mgmt_resource_group_name
          scope: global
    - name: ibm-resource-group
      alias: cs_resource_group
      version: v3.2.15
      variables: *ref_0
    - name: ibm-ocp-vpc
      alias: cluster
      version: v1.13.4
      dependencies:
        - name: subnets
          optional: true
        - name: cos
          optional: true
        - name: vpc
          optional: true
      variables:
        - name: exists
          value: true
        - name: name
          required: true
        - name: vpc_subnet_count
          value: 0
        - name: vpc_subnets
          value: '[]'
        - name: cos_id
          value: ''
        - name: vpc_name
          value: ''
        - name: login
          value: true
    - name: namespace
      alias: tools_namespace
      version: v3.2.2
      default: true
      variables:
        - name: name
          value: tools
    - name: namespace
      alias: openshift-gitops
      version: v3.2.2
      variables:
        - name: name
          value: openshift-gitops
    - name: artifactory
      alias: artifactory
      version: v1.12.2
    - name: cluster-config
      alias: cluster-config
      version: v0.1.2
      variables:
        - name: banner_text
          value: Management
    - name: dashboard
      alias: dashboard
      version: v1.10.14
    - name: ibm-image-registry
      alias: registry
      version: v2.1.2
      variables:
        - name: registry_namespace
          required: true
          scope: global
    - name: openshift-cicd
      alias: openshift-cicd
      version: v1.7.20
    - name: pactbroker
      alias: pactbroker
      version: v1.5.5
    - name: sonarqube
      alias: sonarqube
      version: v1.10.2
    - name: source-control
      alias: git
      version: v1.3.1
    - name: tekton-resources
      alias: tekton-resources
      version: v2.3.0
    - name: console-link-job
      version: v1.0.2
    - name: olm
      version: v1.3.2
    - name: namespace
      alias: tools
      version: v3.2.2
    - name: namespace
      alias: sealed-secret
      version: v3.2.2
    - name: sealed-secret-cert
      version: v1.0.1
    - name: tekton
      version: v2.4.1
  variables:
    - name: ibmcloud_api_key
      type: string
      description: The IBM Cloud api key
    - name: mgmt_resource_group_name
      type: string
      description: The name of the resource group
    - name: region
      type: string
    - name: cs_resource_group_name
      type: string
      description: The name of the resource group
    - name: worker_count
      type: number
      description: >-
        The number of worker nodes that should be provisioned for classic
        infrastructure
      defaultValue: 3
    - name: cluster_flavor
      type: string
      description: The machine type that will be provisioned for classic infrastructure
      defaultValue: bx2.4x16
    - name: mgmt_name_prefix
      type: string
      description: >-
        The prefix name for the service. If not provided it will default to the
        resource group name
      defaultValue: ''
    - name: registry_namespace
      type: string
      description: >-
        The namespace that will be created in the IBM Cloud image registry. If
        not provided the value will default to the resource group
      defaultValue: ''
    - name: git_type
      type: string
      description: The type of source control system (github or gitlab) currently
    - name: git_url
      type: string
      description: The url to the git host (base git host, org, or repo url)
    - name: tools_name
      type: string
      description: The namespace that should be created
      defaultValue: tools
    - name: sealed-secret_name
      type: string
      description: The namespace that should be created
      defaultValue: sealed-secrets
