apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 100-common-services
spec:
  modules:
    - name: ibm-resource-group
      variables:
        - name: resource_group_name
          alias: cs_resource_group_name
          scope: global
        - name: provision
          alias: cs_resource_group_provision
          scope: global
    - name: ibm-access-group
    - name: key-protect
    - name: ibm-object-storage
    - name: ibm-activity-tracker
      variables:
        - name: provision
          value: true
    - name: sysdig
    - name: logdna
    - name: ibm-resource-group
      alias: hpcs_resource_group
      variables:
        - name: provision
          value: false
    - name: hpcs
      variables:
        - name: provision
          value: false
        - name: region
          alias: hpcs_region
        - name: name_prefix
          alias: hpcs_name_prefix
          scope: global
        - name: name
          required: true
      dependencies:
        - name: resource_group
          ref: hpcs_resource_group
    - name: ibm-iam-service-authorization
      alias: flow-log-auth
      variables:
        - name: source_service_name
          value: is
        - name: source_resource_type
          value: flow-log-collector
        - name: target_service_name
          value: cloud-object-storage
        - name: roles
          value:
            - Writer
      dependencies:
        - name: target_resource_group
          ref: resource_group
        - name: source_resource
          ref: source_resource
        - name: source_resource_group
          ref: source_resource_group
        - name: target_resource
          ref: target_resource
    - name: ibm-iam-service-authorization
      alias: vsi-encrypt-auth
      variables:
        - name: source_service_name
          value: server-protect
        - name: target_service_name
          value: hs-crypto
        - name: roles
          value:
            - Reader
      dependencies:
        - name: target_resource_group
          ref: hpcs_resource_group
        - name: source_resource
          ref: source_resource
        - name: source_resource_group
          ref: source_resource_group
        - name: target_resource
          ref: target_resource
    - name: ibm-iam-service-authorization
      alias: cos-encrypt-auth
      variables:
        - name: source_service_name
          value: cloud-object-storage
        - name: target_service_name
          value: hs-crypto
        - name: roles
          value:
            - Reader
      dependencies:
        - name: target_resource_group
          ref: hpcs_resource_group
        - name: source_resource
          ref: source_resource
        - name: source_resource_group
          ref: source_resource_group
        - name: target_resource
          ref: target_resource
  variables:
    - name: cs_resource_group_provision
      value: true
    - name: name_prefix
      alias: cs_name_prefix
    - name: region
    - name: cs_resource_group_name
