apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 140-mzr-workload-openshift
spec:
  modules:
    - name: ibm-resource-group
      alias: kms_resource_group
      variables:
        - name: provision
          value: false
      version: v2.4.6
    - name: ibm-resource-group
      alias: at_resource_group
      variables:
        - name: provision
          value: false
      version: v2.4.6
    - name: ibm-kms
      alias: kms
      variables:
        - name: provision
          value: false
        - name: region
          alias: kms_region
        - name: name_prefix
          alias: kms_name_prefix
          scope: global
          value: ''
      dependencies:
        - name: resource_group
          ref: kms_resource_group
      version: v0.2.0
    - name: ibm-resource-group
      alias: mgmt_resource_group
      variables:
        - name: provision
          value: false
      version: v2.4.6
    - name: ibm-vpc
      alias: management-vpc
      dependencies:
        - name: resource_group
          ref: mgmt_resource_group
      variables:
        - name: provision
          value: false
        - name: name
          required: true
        - name: name_prefix
          alias: mgmt_name_prefix
          scope: global
      version: v1.11.7
    - name: ibm-resource-group
      variables:
        - name: resource_group_name
          alias: workload_resource_group_name
          scope: global
        - name: provision
          alias: workload_resource_group_provision
          scope: global
      version: v2.4.6
    - name: ibm-access-group
      version: v2.3.0
    - name: ibm-vpc
      variables:
        - name: address_prefix_count
          value: 4
        - name: address_prefixes
          value:
            - 10.40.0.0/18
            - 10.50.0.0/18
            - 10.60.0.0/18
            - 10.2.0.0/18
      version: v1.11.7
    - name: ibm-flow-logs
      dependencies:
        - name: target
          ref: ibm-vpc
        - name: cos_bucket
          ref: flow_log_bucket
        - name: resource_group
          ref: resource_group
        - name: auth
          ref: auth
      version: v1.0.0
    - name: ibm-vpc-gateways
      version: v1.5.1
    - name: ibm-vpc-subnets
      alias: worker-subnets
      variables:
        - name: _count
          alias: workload_worker_subnet_count
          scope: global
          value: 3
        - name: label
          value: worker
        - name: ipv4_cidr_blocks
          value:
            - 10.40.10.0/24
            - 10.50.10.0/24
            - 10.60.10.0/24
      dependencies:
        - name: gateways
          ref: ibm-vpc-gateways
        - name: resource-group
          ref: resource_group
        - name: vpc
          ref: ibm-vpc
      version: v1.8.1
    - name: ibm-ocp-vpc
      alias: cluster
      variables:
        - name: disable_public_endpoint
          value: true
        - name: kms_enabled
          value: true
        - name: worker_count
          alias: workload_worker_count
      dependencies:
        - name: subnets
          ref: worker-subnets
        - name: kms_key
          ref: kms_key
        - name: resource-group
          ref: resource_group
        - name: cos
          ref: cos
        - name: sync
          ref: sync
      version: v1.9.0
    - name: ibm-vpc-subnets
      alias: vpe-subnets
      variables:
        - name: _count
          value: 3
        - name: label
          value: vpe
        - name: ipv4_cidr_blocks
          value:
            - 10.40.20.0/24
            - 10.50.20.0/24
            - 10.60.20.0/24
      version: v1.8.1
    - name: ibm-vpc-subnets
      alias: bastion-subnets
      variables:
        - name: _count
          value: 2
        - name: label
          value: bastion
        - name: zone_offset
          value: 1
        - name: ipv4_cidr_blocks
          value:
            - 10.50.30.0/24
            - 10.60.30.0/24
      version: v1.8.1
    - name: ibm-vpc-ssh
      alias: workload_ssh_bastion
      variables:
        - name: label
          value: bastion
      version: v1.6.0
    - name: vsi-bastion
      variables:
        - name: image_name
          scope: module
        - name: kms_enabled
          value: true
      dependencies:
        - name: subnets
          ref: bastion-subnets
        - name: vpcssh
          ref: workload_ssh_bastion
        - name: resource_group
          ref: resource_group
        - name: vpc
          ref: ibm-vpc
        - name: kms_key
          ref: kms-key
      version: v1.7.1
    - name: ibm-resource-group
      alias: cs_resource_group
      variables:
        - name: provision
          value: false
      version: v2.4.6
    - name: ibm-object-storage
      alias: cos
      variables:
        - name: provision
          value: false
        - name: name_prefix
          alias: cs_name_prefix
          scope: global
      dependencies:
        - name: resource_group
          ref: cs_resource_group
      version: v3.3.3
    - name: ibm-kms-key
      variables:
        - name: provision
          value: true
      dependencies:
        - name: kms
          ref: kms
      version: v1.3.0
    - name: ibm-activity-tracker
      variables:
        - name: provision
          value: false
      dependencies:
        - name: resource_group
          ref: at_resource_group
      version: v2.3.0
    - name: sysdig
      variables:
        - name: provision
          value: false
        - name: name_prefix
          alias: cs_name_prefix
          scope: global
      dependencies:
        - name: resource_group
          ref: cs_resource_group
      version: v3.4.0
    - name: ibm-object-storage-bucket
      alias: flow_log_bucket
      variables:
        - name: label
          value: flow-logs
        - name: allowed_ip
          value:
            - 0.0.0.0/0
      version: v0.7.0
    - name: ibm-vpe-gateway
      alias: vpe-cos
      dependencies:
        - name: resource
          ref: cos
        - name: subnets
          ref: vpe-subnets
        - name: sync
          ref: cluster
        - name: resource_group
          ref: resource_group
      version: v1.5.0
    - name: ibm-transit-gateway
      version: v0.1.0
  variables:
    - name: workload_resource_group_name
    - name: region
    - name: ibmcloud_api_key
    - name: name_prefix
      required: true
      alias: workload_name_prefix
    - name: mgmt_resource_group_provision
    - name: workload_resource_group_provision
    - name: cs_resource_group_name
    - name: cs_name_prefix
    - name: mgmt_name_prefix
    - name: hpcs_name
    - name: workload_ssh_vpn_public_key
      value: ''
    - name: workload_ssh_vpn_private_key
      value: ''
    - name: workload_ssh_bastion_public_key
      value: ''
    - name: workload_ssh_bastion_private_key
      value: ''
    - name: workload_ssh_vpn_public_key_file
    - name: workload_ssh_vpn_private_key_file
    - name: workload_ssh_bastion_public_key_file
    - name: workload_ssh_bastion_private_key_file
    - name: kms_service
