apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 140-mzr-workload-openshift
spec:
  modules:
    - name: ibm-resource-group
      alias: mgmt_resource_group
      variables:
        - name: provision
          value: false
    - name: ibm-vpc
      alias: management-vpc
      dependencies:
        - name: resource_group
          ref: mgmt_resource_group
      variables:
        - name: provision
          value: false
        - name: name
          required: true
    - name: ibm-resource-group
      variables:
        - name: resource_group_name
          alias: workload_resource_group_name
          scope: global
        - name: provision
          alias: workload_resource_group_provision
          scope: global
    - name: ibm-vpc
    - name: ibm-vpc-gateways
    - name: ibm-vpc-subnets
      alias: workload-subnets
      variables:
        - name: _count
          value: 3
        - name: label
          value: workload
        - name: ipv4_cidr_blocks
          value:
            - 10.40.10.0/24
            - 10.50.10.0/24
            - 10.60.10.0/24
    - name: ibm-ocp-vpc
      dependencies:
        - name: subnets
          ref: workload-subnets
        - name: resource-group
          ref: resource_group
        - name: cos
          ref: cos
        - name: vpc
          ref: ibm-vpc
        - name: kms
          ref: key-protect
    - name: ibm-vpc-subnets
      alias: vpe-subnets
      variables:
        - name: _count
          value: 3
        - name: label
          value: vpe
        - name: ipv4_cidr_blocks
          value:
            - 10.40.20.0/24
            - 10.50.20.0/24
            - 10.60.20.0/24
    - name: ibm-vpc-subnets
      alias: vpn-subnets
      variables:
        - name: _count
          value: 1
        - name: label
          value: vpn
        - name: ipv4_cidr_blocks
          value:
            - 10.40.30.0/24
    - name: ibm-vpc-subnets
      alias: bastion-subnets
      variables:
        - name: _count
          value: 2
        - name: label
          value: bastion
        - name: ipv4_cidr_blocks
          value:
            - 10.50.30.0/24
            - 10.60.30.0/24
    - name: ibm-vpc-ssh
      alias: workload_ssh_vpn
      variables:
        - name: label
          value: vpn
    - name: vsi-vpn
      dependencies:
        - name: subnets
          ref: vpn-subnets
        - name: vpcssh
          ref: workload_ssh_vpn
        - name: resource_group
          ref: resource_group
        - name: vpc
          ref: ibm-vpc
        - name: bastion
          ref: vsi-bastion
    - name: ibm-vpc-ssh
      alias: workload_ssh_bastion
      variables:
        - name: label
          value: bastion
    - name: vsi-bastion
      dependencies:
        - name: subnets
          ref: bastion-subnets
        - name: vpcssh
          ref: workload_ssh_bastion
        - name: resource-group
          ref: resource_group
        - name: vpc
          ref: ibm-vpc
    - name: ibm-resource-group
      alias: hpcs_resource_group
      variables:
        - name: provision
          value: false
    - name: hpcs
      variables:
        - name: provision
          value: false
        - name: region
          alias: hpcs_region
      dependencies:
        - name: resource_group
          ref: hpcs_resource_group
    - name: ibm-resource-group
      alias: cs_resource_group
      variables:
        - name: provision
          value: false
    - name: ibm-vpc-subnets
      alias: scc-subnets
      variables:
        - name: _count
          value: 1
        - name: label
          value: scc
        - name: ipv4_cidr_blocks
          value:
            - 10.1.1.0/24
    - name: ibm-vpc-ssh
      alias: workload_ssh_scc
      variables:
        - name: label
          value: scc
    - name: scc-collector
      variables:
        - name: scc_registration_key
          alias: workload_scc_registration_key
      dependencies:
        - name: vpcssh
          ref: workload_ssh_scc
        - name: subnets
          ref: scc-subnets
        - name: resource_group
          ref: resource_group
        - name: vpc
          ref: ibm-vpc
    - name: ibm-transit-gateway
  variables:
    - name: workload_resource_group_name
    - name: region
    - name: ibmcloud_api_key
    - name: name_prefix
      required: true
      alias: workload_name_prefix
    - name: mgmt_resource_group_provision
    - name: workload_resource_group_provision
    - name: cs_resource_group_name
    - name: cs_name_prefix
    - name: workload_ssh_vpn_public_key_file
    - name: workload_ssh_vpn_private_key_file
    - name: workload_ssh_bastion_public_key_file
    - name: workload_ssh_bastion_private_key_file
    - name: workload_ssh_scc_public_key_file
    - name: workload_ssh_scc_private_key_file
