name: Push to GHE

on:
  release:
    types:
      - published

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Add GHE remote
        run: |
          git remote add ghe https://${{secrets.GHE_USERNAME}}:${{secrets.GHE_TOKEN}}@github.ibm.com/gsi-labs/ibmcloud-reference-architectures.git
          git fetch ghe

      - name: Push to GHE
        run: |
          git push ghe $(git rev-parse --abbrev-ref HEAD) --follow-tags
      
