name: Verify

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  verify:
    uses: ./.github/workflows/verify-workflow.yaml
    secrets:
      IBMCLOUD_API_KEY: ${{ secrets.IBMCLOUD_API_KEY }}
      OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
      OPENSHIFT_USER: apikey
      OPENSHIFT_PASSWORD: ${{ secrets.IBMCLOUD_API_KEY }}
      GITHUB_PAT: ${{ secrets.TOKEN }}

  release:
    needs: [verify]
    uses: cloud-native-toolkit/action-workflows/.github/workflows/release-module.yaml@v1
    secrets:
      TOKEN: ${{ secrets.TOKEN }}
